### ISSUE TITLE
When I try to catkin_make. it stuck with zeabus_elec_ros_power_dist

### ISSUE THREAD

**Issue by Shayennn** [zeabusTeam/zeabus#2]
I don't know, it's a bug or I've not installed any required library.

And this is an error log, capture by redirect stderr to file.
[catkin_make.err.txt](https://github.com/zeabusTeam/zeabus/files/3115126/catkin_make.err.txt)

**Comment by psychoAB** [comment]
The fix is on the way.

**Comment by psychoAB** [comment]
The fix is in pull request #3

**Comment by Shayennn** [comment]
Due to @SupasanKomonlit accept on the #3 pull request, It might completely be fixed.
